cruise-backend/config/routes.rb
Rails.application.routes.draw do
  resources :parameters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

cruise-backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

cruise-backend/app/models/parameter.rb
class Parameter < ApplicationRecord
end

cruise-backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cruise-backend/app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_parameter, only: %i[show update destroy]

  # GET /parameterrs or /parameters.json
  def index
    @parameters = Parameter.all
    render json: @parameters
  end

  # GET /parameters/1 or /parameters/1.json
  def show
    render json: @parameter
  end

  # POST /parameters or /parameters.json
  def create
    @parameter = Parameter.new(parameter_params)
    if @parameter.save
      render json: @parameter, status: :created
    else
      render json: { errors: @parameter.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /parameters/1 or /parameters/1.json
  def update
    if @parameter.update(parameter_params)
      render json: @parameter, status: :ok
    else
      render json: { errors: @parameter.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # DELETE /parameters/1 or /parameters/1.json
  def destroy
    @parameter.destroy
    render json: { message: "Parameter successfully destroyed" }, status: :ok
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_parameter
    @parameter = Parameter.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def parameter_params
    params.permit(:speed, :distance)
  end
end

cruise-backend/app/helpers/application_helper.rb
module ApplicationHelper
end

cruise-backend/app/helpers/parameters_helper.rb
module ParametersHelper
end

cruise-backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CruiseBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

cruise-backend/app/views/parameters/_form.html.erb
<%= form_with(model: parameter) do |form| %>
  <% if parameter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(parameter.errors.count, "error") %> prohibited this parameter from being saved:</h2>

      <ul>
        <% parameter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :speed, style: "display: block" %>
    <%= form.number_field :speed %>
  </div>

  <div>
    <%= form.label :distance, style: "display: block" %>
    <%= form.number_field :distance %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

cruise-backend/app/views/parameters/_parameter.html.erb
<div id="<%= dom_id parameter %>">
  <p>
    <strong>Speed:</strong>
    <%= parameter.speed %>
  </p>

  <p>
    <strong>Distance:</strong>
    <%= parameter.distance %>
  </p>

</div>

cruise-backend/app/views/parameters/edit.html.erb
<h1>Editing parameter</h1>

<%= render "form", parameter: @parameter %>

<br>

<div>
  <%= link_to "Show this parameter", @parameter %> |
  <%= link_to "Back to parameters", parameters_path %>
</div>

cruise-backend/app/views/parameters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Parameters</h1>

<div id="parameters">
  <% @parameters.each do |parameter| %>
    <%= render parameter %>
    <p>
      <%= link_to "Show this parameter", parameter %>
    </p>
  <% end %>
</div>

<%= link_to "New parameter", new_parameter_path %>

cruise-backend/app/views/parameters/new.html.erb
<h1>New parameter</h1>

<%= render "form", parameter: @parameter %>

<br>

<div>
  <%= link_to "Back to parameters", parameters_path %>
</div>

cruise-backend/app/views/parameters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @parameter %>

<div>
  <%= link_to "Edit this parameter", edit_parameter_path(@parameter) %> |
  <%= link_to "Back to parameters", parameters_path %>

  <%= button_to "Destroy this parameter", @parameter, method: :delete %>
</div>